package com.metar;

/**
 * Data Transfer Object representing a METAR weather report response.
 * <p>
 * On success, {@link #rawMetar} and {@link #friendlyReport} are populated and
 * {@link #error} is {@code null}. On failure, {@link #error} is set and the
 * weather fields are {@code null}.
 */
public class WeatherReportDto {

    /** The ICAO airport code the report was requested for (e.g. {@code KJFK}). */
    public String airportCode;

    /** The raw METAR string as returned by the Aviation Weather Center API. */
    public String rawMetar;

    /** A plain-English weather summary generated by the OpenAI model. */
    public String friendlyReport;

    /** Human-readable error message, populated only when the request fails. */
    public String error;

    /** No-arg constructor required for JSON deserialisation. */
    public WeatherReportDto() {
    }

    /**
     * Constructs a successful weather report response.
     *
     * @param airportCode    the ICAO airport identifier
     * @param rawMetar       the raw METAR string
     * @param friendlyReport the AI-generated plain-English summary
     */
    public WeatherReportDto(String airportCode, String rawMetar, String friendlyReport) {
        this.airportCode = airportCode;
        this.rawMetar = rawMetar;
        this.friendlyReport = friendlyReport;
    }

    /**
     * Creates an error response for the given airport with a descriptive message.
     *
     * @param airportCode the ICAO airport identifier (may be empty if unknown)
     * @param message     a human-readable description of what went wrong
     * @return a {@link WeatherReportDto} with only {@link #airportCode} and {@link #error} set
     */
    public static WeatherReportDto error(String airportCode, String message) {
        WeatherReportDto dto = new WeatherReportDto();
        dto.airportCode = airportCode;
        dto.error = message;
        return dto;
    }
}
